### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by firefly-cpp** [caranha/EvoGCP#2]
Dear Authors (@jair-pereira and @caranha),

this is a very interesting package. Thanks for all the hard work in preparation of this package.

Can you please add a LICENSE in order to allow users easier use of this software?

Thanks!

**Comment by caranha** [comment]
Thank you! I've added the MIT license for the project.

**Comment by firefly-cpp** [comment]
Thank you very much @caranha.

Just another minor request. Is there a possibility to release a version either here on GitHub or Cran?

**Comment by caranha** [comment]
What do you mean by "a version on github"?

**Comment by firefly-cpp** [comment]
Something like this: https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

Thanks.

**Comment by caranha** [comment]
Ah I see.

I will open an issue to create a release (probably related to the 2018
paper), and do it when I have some time :-)
